title: Ilias Sioutis
description: Senior Software Project Manager & Solutions Architect â€” AI-powered healthcare, regulated platforms, cloud & data
theme: jekyll-theme-cayman
google_analytics: G-H9MMF8N06J

